### ISSUE TITLE
图片宽高自适应

### ISSUE THREAD

**Issue by Daotin** [Daotin/fe-tips#197]
```css
.imgBox {
    width: 70px;
    height: 70px;
    img {
        max-width: 100%;
        max-height: 100%;
    }
}
```
